### ISSUE TITLE
Provide AsciidoctorJ 1.6.0 compatibility

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj-groovy-dsl#11]
As discussed in the forum http://discuss.asciidoctor.org/Default-horizontal-style-for-labelled-lists-tp5400p5432.html, some extensions require to use AsciidoctorJ 1.6.x preview, but this cannot be used from the gradle-plugin extensions DSL property due to class name changes.

We could try some `groovish` thing and use dymanic typing to allow compatibility for 1.5.x and 1.6.0 branches, or create a separate branch for 1.6.0.
I am more inclined on the brach option, even if it involves more work, it is much cleaner.

**Comment by robertpanzer** [comment]
I completely agree with you.
If somebody changes the dependency in the Asciidoctor-Gradle-Plugin to use an AsciidoctorJ alpha version I think it should also be possible to change the version of the Groovy DSL.
That should save us a lot of headache.

**Comment by abelsromero** [comment]
Do you think you can make a release on bintray? That way is it available from gradle.

**Comment by robertpanzer** [comment]
Just pushed a release :)
