### ISSUE TITLE
Implement DSL method for docinfo processor

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctorj-groovy-dsl#2]
Implement a DSL method for the DocinfoProcessor introduced in AsciidoctorJ 1.5.2.

(The DocinfoProcessor is very similar to the IncludeProcessor).

See:
- https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/extensions.rb#L248
- https://github.com/asciidoctor/asciidoctorj/blob/master/asciidoctorj-core/src/main/java/org/asciidoctor/extension/DocinfoProcessor.java

**Comment by robertpanzer** [comment]
Fixed with 1f55aa99a

**Comment by mojavelinux** [comment]
:beer:
