### ISSUE TITLE
Need a version that works with asciidoctorj-1.6.0-alpha.7+

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctorj-groovy-dsl#20]
Due to the API change the current extension implementation fails with the 1.6.0 development series of AsciidoctorJ. It would be good to have an alpha release of this library that can work with 1.6.0.

**Comment by robertpanzer** [comment]
Should be fixed with 1.6.0-alpha.2 by cherry-picking your commit from the master branch.
