### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj-groovy-dsl#23]
This PR is to decide the changes and steps for the release of version 2.0.0 aligned with last AsciidoctorJ (currently v2.2.0).

I think the next things need to be done for the next release:
- [x] Update of AsciidoctorJ dependency (and derivated changes) -> (PR https://github.com/asciidoctor/asciidoctorj-groovy-dsl/pull/24)
- [X] Fixes in documentation (as mentioned in https://github.com/asciidoctor/asciidoctorj-groovy-dsl/issues/14#issuecomment-570587303) -> (PR https://github.com/asciidoctor/asciidoctorj-groovy-dsl/pull/28)
- [x] Removal of deprecated methods. This is the moment, we are moving to a major version. -> (PR https://github.com/asciidoctor/asciidoctorj-groovy-dsl/pull/27)
- [x] Build compatibilty with Java 11. Current version of Gradle only works with Java 8. -> (PR https://github.com/asciidoctor/asciidoctorj-groovy-dsl/pull/25)
- [x] Start a CHANGELOG.adoc -> (PR https://github.com/asciidoctor/asciidoctorj-groovy-dsl/pull/26)

Anything else I am missing @robertpanzer?

**Comment by robertpanzer** [comment]
That sounds great!

**Comment by robertpanzer** [comment]
Agreed, let's remove the deprecated methods.

**Comment by abelsromero** [comment]
All is ready. Let me know if you see anything you want me to change in some way.
