### ISSUE TITLE
New version pushed to Maven Central

### ISSUE THREAD

**Issue by paulk-asert** [asciidoctor/asciidoctorj-groovy-dsl#29]
It would be nice if a 2.1.0 version was released to Maven Central with JCenter/Bintray planned for retirement or alternatively if 2.0 could be mirrored over to Maven Central.

**Comment by robertpanzer** [comment]
I published a version 2.0.1  into a staging respository at https://oss.sonatype.org/content/repositories/orgasciidoctor-1245
Could you please try that? It's published from #30.
If it's working for you I'd release that repo to Maven central.

**Comment by paulk-asert** [comment]
Yes, pointing to that repo and setting `asciidoctorj.modules.groovyDsl.version` to 2.0.1 worked for me.
