### ISSUE TITLE
Documentation for include_propcessor might be wrong

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctorj-groovy-dsl#3]
The current example states that `include_processor` is the way to define an IncludeProcessor using the DSL. But version 1.0.0.preview2 will only work if `includeprocessor` is used instead.

**Comment by robertpanzer** [comment]
For 1.0.0.preview2 your statement is correct.
But we have already released 1.0.0.Alpha1:) and that one has both `includeprocessor` and `include_processor`.

**Comment by aalmiray** [comment]
Oh. I was mistaken. I thought Alpha1 came before preview2. Sorry about that.
