### ISSUE TITLE
Add DelegatedTo notation to improve IDE integration

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj-groovy-dsl#5]
I am starting doing some real DSL myself and I find extremely useful the use of DelegatesTo (http://docs.groovy-lang.org/latest/html/api/groovy/lang/DelegatesTo.html) to offer IDE autocomplation and overall facilitate the use of DSLs by users.

What do you think of including it in the project?

I did some local test, adding it here
https://github.com/asciidoctor/asciidoctorj-groovy-dsl/blob/master/src/main/groovy/org/asciidoctor/groovydsl/AsciidoctorExtensions.groovy#L35

and here
https://github.com/asciidoctor/asciidoctorj-groovy-dsl/blob/master/src/main/groovy/org/asciidoctor/groovydsl/AsciidoctorExtensionHandler.groovy#L42
and it worked perfectly in IntellJ.

Showing possible extension...
![image](https://cloud.githubusercontent.com/assets/5781153/15635194/5878ba52-25d8-11e6-8869-aef5a3ab83dc.png)

Showing methods of BlockProcessor
![image](https://cloud.githubusercontent.com/assets/5781153/15635209/a3105a16-25d8-11e6-8eeb-35806ffb2e80.png)

Minimum required Groovy version is 2.1.0, so we should be fine, current version used is 2.3.9

**Comment by robertpanzer** [comment]
@abelsromero This looks really cool! Could you provide a PR for this?

**Comment by abelsromero** [comment]
> Could you provide a PR for this?

Sure, just wanted to check if you agreed.
I'll have some time tomorrow.

**Comment by abelsromero** [comment]
I have noticed a couple of, what I think, are typos, for instance
https://github.com/asciidoctor/asciidoctorj-groovy-dsl/blob/master/src/main/groovy/org/asciidoctor/groovydsl/AsciidoctorExtensionHandler.groovy#L62

It should be in lowercase. I can fix this and add more tests if you agree.

**Comment by robertpanzer** [comment]
Oh yes, that would be nice if you could also fix this!
