### ISSUE TITLE
Improve exception handling in AsciidoctorExtensions.registerTo

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj-groovy-dsl#6]
If there's an exception during registration in [registerTo](https://github.com/asciidoctor/asciidoctorj-groovy-dsl/blob/master/src/main/groovy/org/asciidoctor/groovydsl/AsciidoctorExtensions.groovy#L47) method, the whole process aborts but the _REGISTERED_EXTENSIONS_ is not cleared.
This means that:
- System aborts with unfriendly message
- Correctly declared extensions after point of error are not registered. This behaviour is debatable, but since previous extensions are already registered I think it would be nice that the system skips the error and continues. Another option is to unregister any previous extension, but is that even possible?
- _REGISTERED_EXTENSIONS_ remains with previous values, so if you try to register another extension in another point of the program it fails because it tries ti register the previous one. That affects for example the unit tests, if one fails, all the ones after that fails because of a previous one.

I don't have clear answer for all points, but to begin with I think we should handle any exception to offer a better message, and in case of error clear the _REGISTERED_EXTENSIONS_ list.

**Comment by robertpanzer** [comment]
I am totally in for providing good exception messages that give the user the proper context what has gone wrong.
But from then on I would prefer to fail fast and forward the exception instead of trying to continue processing in any way. 
(That's my personal opinion, but I am also happy with only logging and continuing if there is a majority for it.)

**Comment by abelsromero** [comment]
> But from then on I would prefer to fail fast and forward the exception instead of trying to continue processing in any way.

In fact I prefer that for a first iteration.
Truth is that I cannot think of a real use case for not doing so, except if you're testing or doing some weird stuff like some life rendering.
