### ISSUE TITLE
Version increase

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctorj-groovy-dsl#9]
I saw the other day that the version is `1.0.0.Alpha1` but some changes have been done since the release.
Does it make sense to move it to 1.0.0.Alpha2 and even add the SNAPSHOT word?

**Comment by robertpanzer** [comment]
I'm happy to do an alpha.2 release tomorrow or next week when I find the time. 
Regarding snapshot releases I'm a bit biased though to not do them. 
Just like Andres always prays, using them will make your build unstable. 
I'd rather prefer if the user builds it him-/herself if he/she needs it.

**Comment by abelsromero** [comment]
What I mean is just updating the gradle.properties file, nothing else.

**Comment by robertpanzer** [comment]
Thanks for the hint! Missed that :)
Sorry for getting you wrong!
Will fix it.

**Comment by abelsromero** [comment]
> Sorry for getting you wrong!

No need to apologise, now that I read my message again...it is kinda ambiguous.
